project_id = "ddgnulotktdstycyjsuj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.dynamic-sitemap]
    verify_jwt = false
  [functions.generate-content]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-contact-email]
    verify_jwt = false
